import pytest

from self_healing_agent.agent.service import run_incident
from self_healing_agent.core.models import IncidentPayload


TEST_CASES = [
    (
        "Host Infra",
        "System: GTV , DC: AWS-W , MetricName: Server CPU % , Application: GTV-ONE SEARCH-INFRA for host: 143-251-36-229.vpc.verizon.com , Instance: 143-251-36-229.vpc.verizon.com has Server CPU % >= 99.0",
        {
            "incident_type": "infra_host",
            "service_domain": "GTV",
            "datacenter": "AWS-W",
            "metric_name": ["Server CPU %"],
            "app_name": "GTV-ONE SEARCH-INFRA",
            "host": "143-251-36-229.vpc.verizon.com",
            "instances": ["143-251-36-229.vpc.verizon.com"],
            "instance_host": [],
            "reason": "Server CPU % >= 99.0",
            "warnings": [],
        },
    ),
    (
        "Host Infra",
        "System: DAGV , DC: AWS-W , MetricName: jvm mismatch , Application: DAGV-DAGV-JVM-STATUS for host: AWS-W MCS PNO-DAGV JVM Status Mismatch, 6 missing, 2 extra DAGV-BATCH-CASSANDRAREALTIME-PRD-AW2:DAGV-BATCH-CASSANDRAREALTIME-PRD-AW2 = missing, WLS-DAGV-CXPNOB2-AW2:144-70-44-235.vpc.verizon.com:CXP_PNO_B2C:Server1:13001 = missing, WLS-DAGV-CXPNOB2-AW2:144-70-46-194.vpc.verizon.com:CXP_PNO_B2C:Server3:13003 = missing, WLS-DAGV-CXPNOB2-AW2:144-70-87-170.vpc.verizon.com:DVS_PNO_B2C:Server3:13003 = missing, Instance: Reference List: AWS-West.PNO_JVMList has jvm mismatch >= 0.0",
        {
            "incident_type": "infra_host",
            "service_domain": "DAGV",
            "datacenter": "AWS-W",
            "metric_name": ["jvm mismatch"],
            "app_name": "DAGV-DAGV-JVM-STATUS",
            "host": "AWS-W MCS PNO-DAGV",
            "instances": ["Reference List: AWS-West.PNO_JVMList"],
            "instance_host": [],
            "reason": "jvm mismatch >= 0.0",
            "warnings": ["HOST_NOT_FQDN"],
        },
    ),
    (
        "Host Infra",
        "System: BSUV , DC: TDC , MetricName: /log usage , Application: BSUV-SCMDATA-INFRA for host: tdclpbsuva010.verizon.com , Instance: tdclpbsuva010.verizon.com:/log has /log usage >= 96.0",
        {
            "incident_type": "infra_host",
            "service_domain": "BSUV",
            "datacenter": "TDC",
            "metric_name": ["/log usage"],
            "app_name": "BSUV-SCMDATA-INFRA",
            "host": "tdclpbsuva010.verizon.com",
            "instances": ["tdclpbsuva010.verizon.com:/log"],
            "instance_host": ["tdclpbsuva010.verizon.com"],
            "reason": "/log usage >= 96.0",
            "warnings": [],
        },
    ),
    (
        "Host Infra",
        "System: B6VV , DC: SDC , MetricName: /var/adm/WebSphere usage , Application: B6VV-DVS-INFRA for host: saclpb6vva511.sdc.vzwcorp.com , Instance: saclpb6vva511.sdc.vzwcorp.com:/var/adm/WebSphere has /var/adm/WebSphere usage >= 92.0",
        {
            "incident_type": "infra_host",
            "service_domain": "B6VV",
            "datacenter": "SDC",
            "metric_name": ["/var/adm/WebSphere usage"],
            "app_name": "B6VV-DVS-INFRA",
            "host": "saclpb6vva511.sdc.vzwcorp.com",
            "instances": ["saclpb6vva511.sdc.vzwcorp.com:/var/adm/WebSphere"],
            "instance_host": ["saclpb6vva511.sdc.vzwcorp.com"],
            "reason": "/var/adm/WebSphere usage >= 92.0",
            "warnings": [],
        },
    ),
    (
        "Service DC",
        "Reason: 300% more traffic is observed compared to past window average traffic - 8188.0 System: BVHV, DC: SDC, MetricName: Traffic, Application: BVHV-SAFEGUARD-SSOIGSTREAMPROCESSING",
        {
            "incident_type": "service_dc",
            "service_domain": "BVHV",
            "datacenter": "SDC",
            "metric_name": ["Traffic"],
            "app_name": "BVHV-SAFEGUARD-SSOIGSTREAMPROCESSING",
            "host": None,
            "instances": [],
            "instance_host": [],
            "reason": "300% more traffic is observed compared to past window average traffic - 8188.0",
            "warnings": [],
        },
    ),
    (
        "Service DC",
        "Reason: 1 hosts have alb-502-count >= 7.0, Configured Host Capacity - 0 System: HIVV, DC: AWS-E, MetricName: alb-502-count, Application: HIVV-SOE-Sales-ALB-Logs",
        {
            "incident_type": "service_dc",
            "service_domain": "HIVV",
            "datacenter": "AWS-E",
            "metric_name": ["alb-502-count"],
            "app_name": "HIVV-SOE-Sales-ALB-Logs",
            "host": None,
            "instances": [],
            "instance_host": [],
            "reason": "1 hosts have alb-502-count >= 7.0, Configured Host Capacity - 0",
            "warnings": [],
        },
    ),
    (
        "Service Instance",
        "Reason: Active Threads >= 200.0, Avg Response Time(ms) >= 20000.0 System: B6LV, DC: TDC, MetricName: Active Threads, Avg Response Time(ms), Application: B6LV-ACSS-AMQ, Instance: tdclpb6lva018:ACSS-MQ:acsstr-mq1:5701",
        {
            "incident_type": "service_instance",
            "service_domain": "B6LV",
            "datacenter": "TDC",
            "metric_name": ["Active Threads", "Avg Response Time(ms)"],
            "app_name": "B6LV-ACSS-AMQ",
            "host": None,
            "instances": "tdclpb6lva018:ACSS-MQ:acsstr-mq1:5701",
            "instance_host": [],
            "reason": "Active Threads >= 200.0, Avg Response Time(ms) >= 20000.0",
            "warnings": [],
        },
    ),
    (
        "Service Instance",
        "Reason: Avg Response Time(ms) >= 17086.0 System: B6VV, DC: AWS-W, MetricName: Avg Response Time(ms), Application: B6VV-ORBPM-B2B-NOTIFICATION, Instance: msb2b-834-aws-west2.orbpm.vpc.verizon.com_NOTIFICATION_9098",
        {
            "incident_type": "service_instance",
            "service_domain": "B6VV",
            "datacenter": "AWS-W",
            "metric_name": ["Avg Response Time(ms)"],
            "app_name": "B6VV-ORBPM-B2B-NOTIFICATION",
            "host": None,
            "instances": "msb2b-834-aws-west2.orbpm.vpc.verizon.com_NOTIFICATION_9098",
            "instance_host": [],
            "reason": "Avg Response Time(ms) >= 17086.0",
            "warnings": [],
        },
    ),
    (
        "Service Instance",
        "Reason: 5xx >= 30.0 System: WHUV, DC: TDC, MetricName: 5xx, Application: WHUV-WORKHUB-NXTGEN-INFRA, Instance: WORKHUB_NXTGEN_LOGS|opt|application|access_log",
        {
            "incident_type": "service_instance",
            "service_domain": "WHUV",
            "datacenter": "TDC",
            "metric_name": ["5xx"],
            "app_name": "WHUV-WORKHUB-NXTGEN-INFRA",
            "host": None,
            "instances": "WORKHUB_NXTGEN_LOGS|opt|application|access_log",
            "instance_host": [],
            "reason": "5xx >= 30.0",
            "warnings": [],
        },
    ),
    (
        "Service Instance",
        "Reason: pegaerrors >= 105000.0 System: F5SV, DC: AWS-W, MetricName: pegaerrors, Application: F5SV-RTD-NBX-NEXTGEN, Instance: ERROR: ORA-12541 - Cannot connect. No listener at host nbxmprdr.cqou6muk7g9i.us",
        {
            "incident_type": "service_instance",
            "service_domain": "F5SV",
            "datacenter": "AWS-W",
            "metric_name": ["pegaerrors"],
            "app_name": "F5SV-RTD-NBX-NEXTGEN",
            "host": None,
            "instances": "ERROR: ORA-12541 - Cannot connect. No listener at host nbxmprdr.cqou6muk7g9i.us",
            "instance_host": ["nbxmprdr.cqou6muk7g9i.us"],
            "reason": "pegaerrors >= 105000.0",
            "warnings": [],
        },
    ),
    (
        "Service Instance",
        "Reason: oracle-db-sp-queue-status >= 3.0 System: BRHV, DC: TDC, MetricName: oracle-db-sp-queue-status, Application: BRHV-BRHV_SPLEX-Common-Operations, Instance: tdclpbrhvd008.verizon.com:Post:cjcmeast_revo_q4:2058",
        {
            "incident_type": "service_instance",
            "service_domain": "BRHV",
            "datacenter": "TDC",
            "metric_name": ["oracle-db-sp-queue-status"],
            "app_name": "BRHV-BRHV_SPLEX-Common-Operations",
            "host": None,
            "instances": "tdclpbrhvd008.verizon.com:Post:cjcmeast_revo_q4:2058",
            "instance_host": [],
            "reason": "oracle-db-sp-queue-status >= 3.0",
            "warnings": [],
        },
    ),
    (
        "Service Instance",
        "Reason: 5xx >= 30.0 System: WHUV, DC: TDC, MetricName: 5xx, Application: WHUV-WORKHUB-NXTGEN-INFRA, Instance: WORKHUB_NXTGEN_LOGS|opt|application|access_log",
        {
            "incident_type": "service_instance",
            "service_domain": "WHUV",
            "datacenter": "TDC",
            "metric_name": ["5xx"],
            "app_name": "WHUV-WORKHUB-NXTGEN-INFRA",
            "host": None,
            "instances": "WORKHUB_NXTGEN_LOGS|opt|application|access_log",
            "instance_host": [],
            "reason": "5xx >= 30.0",
            "warnings": [],
        },
    ),
    (
        "System Instance",
        "Reason: CW_ReadIOPS >= 20000.0 System: F5SV, DC: AWS-E, MetricName: CW_ReadIOPS, Application: F5SV-F5SV Databases-OMP, Host: ompeprd",
        {
            "incident_type": "system_instance",
            "service_domain": "F5SV",
            "datacenter": "AWS-E",
            "metric_name": ["CW_ReadIOPS"],
            "app_name": "F5SV-F5SV Databases-OMP",
            "host": "ompeprd",
            "instances": [],
            "instance_host": [],
            "reason": "CW_ReadIOPS >= 20000.0",
            "warnings": ["HOST_NOT_FQDN"],
        },
    ),
    (
        "System Instance",
        "Reason: ibmmqdepth_TDCqueues >= 32000.0 System: DAGV, DC: TDC, MetricName: ibmmqdepth_TDCqueues, Application: DAGV-CPF_MQ-IBMMQ, Host: tdclpdagva102.tdc.vzwcorp.com",
        {
            "incident_type": "system_instance",
            "service_domain": "DAGV",
            "datacenter": "TDC",
            "metric_name": ["ibmmqdepth_TDCqueues"],
            "app_name": "DAGV-CPF_MQ-IBMMQ",
            "host": "tdclpdagva102.tdc.vzwcorp.com",
            "instances": [],
            "instance_host": [],
            "reason": "ibmmqdepth_TDCqueues >= 32000.0",
            "warnings": [],
        },
    ),
    (
        "System DC",
        "Reason: 1 hosts have oracle-db-session-blocker >= 300.0 System: EV6V, DC: SDC, MetricName: oracle-db-session-blocker, Application: EV6V-EVV-Databases-VIP",
        {
            "incident_type": "system_dc",
            "service_domain": "EV6V",
            "datacenter": "SDC",
            "metric_name": ["oracle-db-session-blocker"],
            "app_name": "EV6V-EVV-Databases-VIP",
            "host": None,
            "instances": [],
            "instance_host": [],
            "reason": "1 hosts have oracle-db-session-blocker >= 300.0",
            "warnings": [],
        },
    ),
]


@pytest.mark.parametrize(
    ("label", "incident_details", "expected_parsed_incident"),
    TEST_CASES,
)
def test_parse_raw_incident_text_quick_test_main_scenarios(
    label: str,
    incident_details: str,
    expected_parsed_incident: dict,
) -> None:
    result = run_incident(IncidentPayload(incident_details=incident_details))
    assert result["status"] == "processed", f"unexpected status for {label}"
    assert result["parsed_incident"] == expected_parsed_incident

# To run test:
# cd self_healing_agent
# uv run --with pytest pytest -q tests/nodes/parse_raw_incident_text.py